CONFIG:
  IA:
    HOSTLIB_DZTOL: 0.01 0 0
    SEARCHEFF_zHOST_FILE: /project2/rkessler/SURVEYS/SDSS/USERS/BAP37/BS20-PHOT/SDSS/ZEFF/NEW-WORKING.DAT
    HOSTLIB_WGTMAP_FILE: /project2/rkessler/SURVEYS/SDSS/USERS/BAP37/BS20-PHOT/SDSS/SDSS-WGT.V3.DAT
    SEARCHEFF_PIPELINE_EFF_FILE: /project2/rkessler/SURVEYS/SDSS/USERS/BAP37/BS20-PHOT/SDSS/SN-EFF-NEW.DAT
    SEARCHEFF_PIPELINE_LOGIC_FILE: $SNDATA_ROOT/models/searcheff/SEARCHEFF_PIPELINE_LOGIC.DAT
    GENMAG_SMEAR: 1.0e-06
    GENPEAK_SALT2ALPHA: 0.145
    HOSTLIB_SCALE_PROPERTY_ERR: 0.0(LOGMASS),0.0(LOGSFR),0.0(LOGsSFR),0.0(COLOR)
    GENMAG_SMEAR_MODELNAME: C11
    GENMAG_SMEAR_SCALE: 0.0001
    GENMAG_SMEAR_SCALE(c): 0,0
    GENMAG_OFF_GLOBAL: -0.12
    GENPDF_OPTMASK: 1
    HOSTLIB_MSKOPT: 2
    GENMODEL: $DES_USERS/mvincenzi/SALT3.K21-Frag-unoU
    GENPDF_FILE: /project2/rkessler/SURVEYS/SDSS/USERS/BAP37/BS20-PHOT/PS1+SDSS/8-20-22-GENPDF.DAT
    BASE: /project2/rkessler/SURVEYS/SDSS/USERS/BAP37/BBC_paper_2/SDSS_usable/SIMGEN_SDSS_SALT2_data.input
    HOSTLIB_FILE: /project2/rkessler/SURVEYS/SDSS/USERS/BAP37/BBC_paper_2/PHOT_HOSTLIBS/SDSS-PHOT-BS20.HOSTLIB
  PECIAX:
    HOSTLIB_MSKOPT: 2
    HOSTLIB_FILE: /project2/rkessler/SURVEYS/SDSS/USERS/BAP37/BBC_paper_2/PHOT_HOSTLIBS/SDSS-PHOT-BS20.HOSTLIB
    HOSTLIB_DZTOL: 0.01 0 0
    SEARCHEFF_zHOST_FILE: /project2/rkessler/SURVEYS/SDSS/USERS/BAP37/BS20-PHOT/SDSS/ZEFF/NEW-WORKING.DAT
    HOSTLIB_WGTMAP_FILE: /project2/rkessler/SURVEYS/SDSS/USERS/BAP37/BS20-PHOT/SDSS/SDSS-WGT.V3.DAT
    SEARCHEFF_PIPELINE_EFF_FILE: /project2/rkessler/SURVEYS/SDSS/USERS/BAP37/BS20-PHOT/SDSS/SN-EFF-NEW.DAT
    SEARCHEFF_PIPELINE_LOGIC_FILE: $SNDATA_ROOT/models/searcheff/SEARCHEFF_PIPELINE_LOGIC.DAT
    BASE: /project2/rkessler/SURVEYS/SDSS/USERS/BAP37/BBC_paper_2/SDSS_usable/MVCC/sims_cc/sn_iax_CorrR14.input
  PECIA91BG:
    HOSTLIB_MSKOPT: 2
    HOSTLIB_FILE: /project2/rkessler/SURVEYS/SDSS/USERS/BAP37/BBC_paper_2/PHOT_HOSTLIBS/SDSS-PHOT-BS20.HOSTLIB
    HOSTLIB_DZTOL: 0.01 0 0
    SEARCHEFF_zHOST_FILE: /project2/rkessler/SURVEYS/SDSS/USERS/BAP37/BS20-PHOT/SDSS/ZEFF/NEW-WORKING.DAT
    HOSTLIB_WGTMAP_FILE: /project2/rkessler/SURVEYS/SDSS/USERS/BAP37/BS20-PHOT/SDSS/SDSS-WGT.V3.DAT
    SEARCHEFF_PIPELINE_EFF_FILE: /project2/rkessler/SURVEYS/SDSS/USERS/BAP37/BS20-PHOT/SDSS/SN-EFF-NEW.DAT
    SEARCHEFF_PIPELINE_LOGIC_FILE: $SNDATA_ROOT/models/searcheff/SEARCHEFF_PIPELINE_LOGIC.DAT
    BASE: /project2/rkessler/SURVEYS/SDSS/USERS/BAP37/BBC_paper_2/SDSS_usable/MVCC/sims_cc/sn_ia91bg_stretchCorr.input
  II_TEMPLATES:
    HOSTLIB_MSKOPT: 2
    HOSTLIB_FILE: /project2/rkessler/SURVEYS/SDSS/USERS/BAP37/BBC_paper_2/PHOT_HOSTLIBS/SDSS-PHOT-BS20.HOSTLIB
    HOSTLIB_DZTOL: 0.01 0 0
    SEARCHEFF_zHOST_FILE: /project2/rkessler/SURVEYS/SDSS/USERS/BAP37/BS20-PHOT/SDSS/ZEFF/NEW-WORKING.DAT
    HOSTLIB_WGTMAP_FILE: /project2/rkessler/SURVEYS/SDSS/USERS/BAP37/BS20-PHOT/SDSS/SDSS-WGT.V3.DAT
    SEARCHEFF_PIPELINE_EFF_FILE: /project2/rkessler/SURVEYS/SDSS/USERS/BAP37/BS20-PHOT/SDSS/SN-EFF-NEW.DAT
    SEARCHEFF_PIPELINE_LOGIC_FILE: $SNDATA_ROOT/models/searcheff/SEARCHEFF_PIPELINE_LOGIC.DAT
    BASE: /project2/rkessler/SURVEYS/SDSS/USERS/BAP37/BBC_paper_2/SDSS_usable/MVCC/sims_cc_revised_maria/sn_ii_v19_dustR14.input
    DNDZ: 0.7*CC_S15
  Ibc_TEMPLATES:
    HOSTLIB_MSKOPT: 2
    HOSTLIB_FILE: /project2/rkessler/SURVEYS/SDSS/USERS/BAP37/BBC_paper_2/PHOT_HOSTLIBS/SDSS-PHOT-BS20.HOSTLIB
    HOSTLIB_DZTOL: 0.01 0 0
    SEARCHEFF_zHOST_FILE: /project2/rkessler/SURVEYS/SDSS/USERS/BAP37/BS20-PHOT/SDSS/ZEFF/NEW-WORKING.DAT
    HOSTLIB_WGTMAP_FILE: /project2/rkessler/SURVEYS/SDSS/USERS/BAP37/BS20-PHOT/SDSS/SDSS-WGT.V3.DAT
    SEARCHEFF_PIPELINE_EFF_FILE: /project2/rkessler/SURVEYS/SDSS/USERS/BAP37/BS20-PHOT/SDSS/SN-EFF-NEW.DAT
    SEARCHEFF_PIPELINE_LOGIC_FILE: $SNDATA_ROOT/models/searcheff/SEARCHEFF_PIPELINE_LOGIC.DAT
    BASE: /project2/rkessler/SURVEYS/SDSS/USERS/BAP37/BBC_paper_2/SDSS_usable/MVCC/sims_cc_revised_maria/sn_ibc_v19_dustR14.input
    DNDZ: 0.3*CC_S15
  GLOBAL:
    NGEN_UNIT: 50
    RANSEED_CHANGE: 10 12333
    BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2b.TEMPLATE 10
  GENVERSION: PIP_BP-SDSS-MOCK_SIMDATASDSS_P21
OUTPUT:
  name: SIMDATASDSS_P21
  output_dir: /scratch/midway2/rkessler/PIPPIN_OUTPUT/BP-SDSS-MOCK/1_SIM/SIMDATASDSS_P21
  hash_file: /scratch/midway2/rkessler/PIPPIN_OUTPUT/BP-SDSS-MOCK/1_SIM/SIMDATASDSS_P21/hash.txt
  done_file: /scratch/midway2/rkessler/PIPPIN_OUTPUT/BP-SDSS-MOCK/1_SIM/SIMDATASDSS_P21/done.txt
  types_dict:
    IA:
    - 1
    - 101
    NONIA:
    - 11
    - 111
    - 91
    - 191
    - 20
    - 120
    - 20
    - 120
  types:
    1: Ia
    11: II
    20: II
    91: II
    101: Ia
    111: II
    120: II
    191: II
  blind: false
  genversion: PIP_BP-SDSS-MOCK_SIMDATASDSS_P21
  genprefix: PIP_BP-SDSS-MOCK_SIMDATASdcc44
  ranseed_change: true
  ranseed_change_val: 10 12333
  sim_folders:
  - /scratch/midway2/rkessler/SNDATA_ROOT/SIM/PIP_BP-SDSS-MOCK_SIMDATASDSS_P21-0001
  - /scratch/midway2/rkessler/SNDATA_ROOT/SIM/PIP_BP-SDSS-MOCK_SIMDATASDSS_P21-0002
  - /scratch/midway2/rkessler/SNDATA_ROOT/SIM/PIP_BP-SDSS-MOCK_SIMDATASDSS_P21-0003
  - /scratch/midway2/rkessler/SNDATA_ROOT/SIM/PIP_BP-SDSS-MOCK_SIMDATASDSS_P21-0004
  - /scratch/midway2/rkessler/SNDATA_ROOT/SIM/PIP_BP-SDSS-MOCK_SIMDATASDSS_P21-0005
  - /scratch/midway2/rkessler/SNDATA_ROOT/SIM/PIP_BP-SDSS-MOCK_SIMDATASDSS_P21-0006
  - /scratch/midway2/rkessler/SNDATA_ROOT/SIM/PIP_BP-SDSS-MOCK_SIMDATASDSS_P21-0007
  - /scratch/midway2/rkessler/SNDATA_ROOT/SIM/PIP_BP-SDSS-MOCK_SIMDATASDSS_P21-0008
  - /scratch/midway2/rkessler/SNDATA_ROOT/SIM/PIP_BP-SDSS-MOCK_SIMDATASDSS_P21-0009
  - /scratch/midway2/rkessler/SNDATA_ROOT/SIM/PIP_BP-SDSS-MOCK_SIMDATASDSS_P21-0010
  SURVEY: SDSS
  SURVEY_ID: 1
  photometry_dirs:
  - /scratch/midway2/rkessler/PIPPIN_OUTPUT/BP-SDSS-MOCK/1_SIM/SIMDATASDSS_P21/PIP_BP-SDSS-MOCK_SIMDATASDSS_P21-0001
  - /scratch/midway2/rkessler/PIPPIN_OUTPUT/BP-SDSS-MOCK/1_SIM/SIMDATASDSS_P21/PIP_BP-SDSS-MOCK_SIMDATASDSS_P21-0002
  - /scratch/midway2/rkessler/PIPPIN_OUTPUT/BP-SDSS-MOCK/1_SIM/SIMDATASDSS_P21/PIP_BP-SDSS-MOCK_SIMDATASDSS_P21-0003
  - /scratch/midway2/rkessler/PIPPIN_OUTPUT/BP-SDSS-MOCK/1_SIM/SIMDATASDSS_P21/PIP_BP-SDSS-MOCK_SIMDATASDSS_P21-0004
  - /scratch/midway2/rkessler/PIPPIN_OUTPUT/BP-SDSS-MOCK/1_SIM/SIMDATASDSS_P21/PIP_BP-SDSS-MOCK_SIMDATASDSS_P21-0005
  - /scratch/midway2/rkessler/PIPPIN_OUTPUT/BP-SDSS-MOCK/1_SIM/SIMDATASDSS_P21/PIP_BP-SDSS-MOCK_SIMDATASDSS_P21-0006
  - /scratch/midway2/rkessler/PIPPIN_OUTPUT/BP-SDSS-MOCK/1_SIM/SIMDATASDSS_P21/PIP_BP-SDSS-MOCK_SIMDATASDSS_P21-0007
  - /scratch/midway2/rkessler/PIPPIN_OUTPUT/BP-SDSS-MOCK/1_SIM/SIMDATASDSS_P21/PIP_BP-SDSS-MOCK_SIMDATASDSS_P21-0008
  - /scratch/midway2/rkessler/PIPPIN_OUTPUT/BP-SDSS-MOCK/1_SIM/SIMDATASDSS_P21/PIP_BP-SDSS-MOCK_SIMDATASDSS_P21-0009
  - /scratch/midway2/rkessler/PIPPIN_OUTPUT/BP-SDSS-MOCK/1_SIM/SIMDATASDSS_P21/PIP_BP-SDSS-MOCK_SIMDATASDSS_P21-0010
